### ISSUE TITLE
filter out properties underneath non-selected selector options from `staged-config`

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#166]
Here is a section generated when we run `staged-config` on our environment:
```yaml
 .properties.uaa_database:
    value: internal_mysql
  .properties.uaa_database.external.uaa_password:
    value:
      secret: '***'
```

Since we have `uaa_database` set to `internal_mysql`, the `.properties.uaa_database.external.uaa_password` part is an extraneous info to us.

We'd like to remove the unnecessary `selector` sections like this to make the configuration dumped from `staged-config` more reuseable to deploy other fundations.

The examples of expected filtered output are as follows:
1. Original:
```yaml
.properties.uaa:
  value: internal
.properties.uaa.internal.password_min_special:
  value: 0
.properties.uaa.internal.password_min_uppercase:
  value: 0
.properties.uaa.ldap.credentials:
  value: {}
.properties.uaa.ldap.group_search_filter:
  value: member={0}
```
After:
```yaml
.properties.uaa:
  value: internal
.properties.uaa.internal.password_min_special:
  value: 0
.properties.uaa.internal.password_min_uppercase:
  value: 0
```

2. Original:
```yaml
 .properties.uaa_database:
    value: internal_mysql
  .properties.uaa_database.external.uaa_password:
    value:
      secret: '***'
```
After
```yaml
 .properties.uaa_database:
    value: internal_mysql
```
