### ISSUE TITLE
add --replace-creds to `staged-config`

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#169]
The returned payload from `staged-config` is like:
```yaml
# something
  .properties.system_database.external.nfsvolume_password:
    value:
      secret: '***'
  .properties.system_database.external.notifications_password:
    value:
      secret: '***'
# some more thing
```

This is not helpful when we want to use this configuration on another fundation, since there are a lot of the places we need to clean up. We'd like to have a flag like `--replace-creds` to replace the 
 triple asterisk to interpolatable placeholder.

Continue with the example above, the result output we want would be like:
```yaml
# something
  .properties.system_database.external.nfsvolume_password:
    value:
      secret: '((system_database_external_nfsvolume_password.secret))'
  .properties.system_database.external.notifications_password:
    value:
      secret: '((system_database_external_notifications_password.secret))'
# some more thing
```

This hopefully enables us to do something like:
`om -t some.other.foundation config-product -p cf -c <(om staged-config -p cf --replace-creds) -l creds.yml`.

**Comment by mcwumbly** [comment]
how about `--include-placeholders` instead?

also, a separate question: are the `***` ever helpful? maybe the properties be completely excluded by default?

**Comment by fredwangwang** [comment]
> how about --include-placeholder instead?

I think this is fine to our side since we don't have a strong opinion regarding the flag names.

> also, a separate question: are the *** ever helpful? maybe the properties be completely excluded by default?

I agree. Seems like there are two possibilities that the user want's to dump the data:
1. Reconfigure some properties for the same foundation
1. Port the configuration to some other foundations.

For the first case the user don't really care about `***` that is already used by deployed vms. for the later case we want to provide `--include-placeholder` to replace the asterisk to placeholders. 

So what about we have a PR to do two modifications?
1. change the default behavior to exclude asterisk.
1. add the flag to support additonal behavior

**Comment by fredwangwang** [comment]
Also, do you have any preference in the naming schema of the placeholders?

our proposed schema is like:
```python
'_'.join(name.split('.')[2:]) + '.' + attr_name
```

For example:
```yaml
 .properties.system_database.external.nfsvolume_password:
    value:
      secret: '***'
```
has the placeholder: `((system_database_external_nfsvolume_password.secret))`

It all looks fine to me, but the only fear would be **name collison**

Like, would it be possible that there are two properties which are like 

`.properties.some.attr` 

and 

`.product-name.some.attr`?

**Comment by mcwumbly** [comment]
> So what about we have a PR to do two modifications?
> 
> 1. change the default behavior to exclude asterisk.
> 2. add the flag to support additonal behavior

Sounds good. If it's straightforward to separate those PRs, I think it may help, but if that makes things more complicated, they can come in together.

> Also, do you have any preference in the naming schema of the placeholders?

What about replacing dot (`.`) with double underbars (`__`), so `.properties.system_database.external.nfsvolume_password` becomes `system_database__external__nfsvolume_password`

What value does the `attr` suffix provide?

**Comment by fredwangwang** [comment]
> What about replacing dot (.) with double underbars (__)

Just think about (`-`), so we can distinguish from (`some_name`) and avoid type `__`.

> What value does the attr suffix provide?

It's just a way to express the format. Let me come up with two imaginary example:
```
.properties.api_endpoint.password:
  value:
    secret: '***'
```

```
.credhub.api_endpoint.password:
  value:
    secret: '***'
```
With `'-'.join(name.split('.')[2:]) + '.' + attr_name`, they both become `api_endpoint-password.secret`

Is this example ever possible in real situation? 

--

anyway, it doesn't affect get rid of `***` as a default behavior, going to do that for now

**Comment by mcwumbly** [comment]
these names are not very pretty either way, so maybe we just keep the `properties` and/or `credhub` prefix in your example.

I'm still unclear why we want `.secret` appended to the end though, and want to bounce the `-` vs. `__` vs. `.` substitution around with someone else on our team as well... so, will circle back on that question.

> anyway, it doesn't affect get rid of `***` as a default behavior, going to do that for now

sounds good.

**Comment by davewalter** [comment]
Does the API for a 2.2 Ops Manager still obscure the secrets with `***` now that they are no longer included in the rendered BOSH manifest, or does it return the Credhub accessor that it injects instead? If it doesn't obscure the credentials anymore, then anything we do to solve this will stop working and we'll need to rethink.

**Comment by jtarchie** [comment]
@davewalter, great question. We'll reach out to the team and see if they have any insight.

**Comment by jtarchie** [comment]
@davewalter: After discussing with OM team, the credhub integration output will only apply to `manifests` endpoint. The `properties` endpoint will still extract the `***` for a credential.

@mcwumbly: The `.secret` is a placeholder for the fact that there are different types of credentials. For example, there is a cert, which can have `cert`, `private_key`, etc. We'd like to use the YAML interpolation dot notation, for YAML readability.

For example, a `vars.yml` far away...

```yaml
some_property_name:
  private_key: ----
  cert: ----
```

This could be used in a `config.yml` like so.

```yaml
.properties.some_property_name
  private_key: ((some_property_name.private_key))
  cert: ((some_property_name.cert))
```

As for the versus notation, `-` or `_` is preferable, as if we introduce `.` into the name generation it affects the `creds.yml` format.

All of that being said, our ultimate goal is to have a way of extract credentials into a separate file. We are flexible on the naming schema of the that, as long as the goal is met.

**Comment by jtarchie** [comment]
After discussing with @mcwumbly, we've agree on a PR (that could change) with the following interface.

As a platform operator,
When I run `staged-config` with ` --include-placeholder`,
Then I have a config that has creds replaced `((full_property_name))` placeholders.

For example:

```yaml
.properties.some_property_name
  private_key: ((.properties.some_property_name.private_key))
  cert: ((.properties.some_property_name.cert))
```

**Comment by jtarchie** [comment]
And for reference, so we have some place to remind ourselves that `bosh int` does this.

When a dot notation is used for the var, it can be specified two different ways in the supplied vars-file.

For example,

manifest.yml

```yaml
.properties.some-property
  value:
    secret: ((.properties.some-property.secret))
```

The var can be specified as

```
".properties":
  some-property:
    secret: super-secure-password
```

or

```
".properties.some-property.secret": super-secure-password
```

They are both valid!? I didn't know.
