### ISSUE TITLE
 should `staged-director-config` remove the guids

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#176]
We understand why `om` returns guids in the output of this command (OpsManager relies on guids for internal purposes in the API).

However, as a user of `om` who doesn't care about the internals of the OpsManager API, we feel like giving the guid when we use this command needlessly complicates our payload. For example, when using `staged-director-config` for vsphere, we get back the following:
```
    az-configuration:
    - guid: caf56be890aab8471cfc
      name: us-central1-a
    - guid: 294ed5d30add4ba0bb1d
      name: us-central1-b
    - guid: 264c554f584074e4b40e
      name: us-central1-c
```
As a user of OpsManager, I want to operate in the UI as little as possible while mimicking the behavior/view of the UI as much as possible. Therefore, what would mirror this experience the closest would be to return:
```
    az-configuration:
    - name: us-central1-a
    - name: us-central1-b
    - name: us-central1-c
``` 
Which is just as informative, but with less clutter. 

We are willing to create a PR to create this behavior, but are willing to discuss further if there is a higher need to include the guids in the response.

As an additional thought: `configure-director` will already handle a `PUT` to OpsManager without the user having to include the guids in the payload. Implementing similar behavior for `staged-director-config` will help unify the experience.
