### ISSUE TITLE
placeholder name is not interpolatable

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#178]
For `collection` types in `staged-config` command, we used the format 

`.properties.some-collection[Idx].inner-prop`, sadly it doesn't work for bosh interpolation.  The regex in bosh, which is \(\((!?[-/\.\w\pL]+)\)\), doesn't support [ & ] in variable name.

So it would be a simple fix to change from:
https://github.com/pivotal-cf/om/blob/638511cffd6b6adccffff461d4c9a60530b18d20/commands/staged_config.go#L186

To: 
```go
 innerValueNamePrefix := name + strconv.Itoa(index) + "." + innerKey.(string)
```

An example:
output snippet:
```yaml
.properties.networking_poe_ssl_certs:
  - certificate:
      cert_pem: ((.properties.networking_poe_ssl_certs0.certificate.cert_pem))
      private_key_pem: ((.properties.networking_poe_ssl_certs0.certificate.private_key_pem))
```

vars-file:
```yaml
.properties.networking_poe_ssl_certs0.certificate:
  cert_pem: hello
  private_key_pem: world
```

Generated:
```yaml
.properties.networking_poe_ssl_certs:
- certificate:
    cert_pem: hello
    private_key_pem: world
```

**Comment by jtarchie** [comment]
We need to discuss this, again.

It seems that the parameter name schema may not work well for us -- the dot separator. The bosh library we are using for interpolation has a [_feature_](https://github.com/cloudfoundry/bosh-cli/issues/437), which doesn't allow dot values to be defines across multiple vars files.

**Comment by fredwangwang** [comment]
Closing, PR #181 is merged.

**Comment by mcwumbly** [comment]
Hey @fredwangwang and @jtarchie - @heycait and I are going through and accepting stories and had some interesting observations and discussion when it came to this feature.

First off, looks like things currently work now such that we have variable name placeholders which look like:

```
product-properties:
  .properties.credhub_hsm_provider_client_certificate:
    value:
      cert_pem: ((properties_credhub_hsm_provider_client_certificate.cert_pem))
      private_key_pem: ((properties_credhub_hsm_provider_client_certificate.private_key_pem))
```

And these can now be interpolated with a vars-file that looks like this:

```
properties_credhub_hsm_provider_client_certificate:
  cert_pem: hello
  private_key_pem: world
```

We were wondering whether this is how we ultimately want it to be, or whether we want to have a `.` before `certificate` though, like this:

```
product-properties:
  .properties.credhub_hsm_provider_client_certificate:
    value:
      cert_pem: ((properties_credhub_hsm_provider_client.certificate.cert_pem))
      private_key_pem: ((properties_credhub_hsm_provider_client.certificate.private_key_pem))
```

which would allow a vars-file to look like this:

```
properties_credhub_hsm_provider_client:
  certificate:
    cert_pem: hello
    private_key_pem: world
```

---

Finally, this brought up a higher-level question to us about whether we want `om` to have any built-in features for interpolation at all.  Would we be better off just relying on `bosh` for interpolation?  One reason this question is coming up for me now is due to this other issue opened this morning, which is asking about leaning on other interpolation features that BOSH has like `--ops-file`...
