### ISSUE TITLE
update `config-template` to reflect the placeholder names provided in `staged-config`

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#189]
In `stage-config` the `--include-placeholder` flag provided params with names, using `_` as the separator (not the `.`).

This means `config-template` would have params also in the format.

For example,

```yaml
product-properties:
  .properties.some-name:
    value:
      identity: ((.properties.some-name.identity))
      password: ((.properties.some-name.password))
```

would look like

```yaml
product-properties:
  .properties.some-name:
    value:
      identity: ((properties_some-name.identity))
      password: ((properties_some-name.password))
```
