### ISSUE TITLE
Unable to upload cf gorouter/uaa certificate using configure-product

### ISSUE THREAD

**Issue by ynbchery** [pivotal-cf/om#201]
I have this issue where I can't figure out how to upload a certificate to the cf product using om cli with a yaml config file. I've tried 2 different ways & I'm always getting the same error message:

**With double-quotes**
`cert_pem: "-----BEGIN CERTIFICATE-----\r\nMIIERTCCAy2gAwIBAgIV********\r\n****"`
**Using the pipe**
```yaml
cert_pem: |
  -----BEGIN CERTIFICATE-----
  MIIERTCCAy2gAwIBAgIVAPfJC+zSpPc/sDffsBEh5tj5vbKFMA0GCSqGSIb3DQEB
  CwUAMB8xCzAJBgNVBAYTAlVTMRAwDgYDVQQKDAdQaXZvdGFsMB4XDTE4MDcwMTIw
  MzgzOVoXDTIwMDcwMTIwMzgzOVowVTELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB1Bp
  dm90YWwxNDAyBgNVBAMMKyouc3lzLnVzLWVhc3QtMi5kZXZ0c3QucGNmLmdjcy5u
  ****************************************************************
  ****************************************************************
  ****************************************************************
  ****************************************************************
  -----END CERTIFICATE-----
```
to take a look at the formatting of my config file, see the attached (keys & secrets were randomly generated * not in actual use):
[cf.txt](https://github.com/pivotal-cf/om/files/2172307/cf.txt)

om -t $OM_TARGET -u $OM_USERNAME -p $OM_PASSWORD -k configure-product -c cf.yml -n cf

configuring product...
setting properties
could not execute "configure-product": failed to configure product: request failed: unexpected response:
HTTP/1.1 422 Unprocessable Entity
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Sat, 07 Jul 2018 00:17:21 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=15552000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 0407214f-5ea1-41aa-99f8-6b5d2faec036
X-Runtime: 1.829693
X-Xss-Protection: 1; mode=block

83
{"errors":{".properties.networking_poe_ssl_certs":["Record 1: Certificate can't be blank","Record 1: Certificate can't be blank"]}}
0

I'm able to configure all other properties of the cf tile except for the go router & uaa certs. Any idea?

**Comment by fredwangwang** [comment]
It needs to be in this particular format:
```yaml
  ".properties.networking_poe_ssl_certs":
    value:
    - name: <CERT_NAME_HERE>
      certificate:
        cert_pem: <CERT_HERE>
        private_key_pem: <PRIVATE_KEY_HERE>
```

**Comment by scottgai** [comment]
got same issue even with format suggested by @fredwangwang 

`$ ./om  -u admin -p changeme -k -t 192.168.111.66 configure-product -n cf -c ./cf-config1.yml
configuring product...
setting properties
could not execute "configure-product": failed to configure product: request failed: unexpected response:
HTTP/1.1 422 Unprocessable Entity
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 09 Jul 2018 13:46:44 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=15552000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 60b1f8a2-a587-439e-bc86-839eab64b190
X-Runtime: 2.332154
X-Xss-Protection: 1; mode=block

5c
{"errors":{".properties.networking_poe_ssl_certs":["Record 1: Certificate can't be blank"]}}
0`

config file:
`$ cat cf-config1.yml
product-properties:
  ".properties.networking_poe_ssl_certs":
    value:
    - name: "ha&router"
      certificate:
        cert_pem: "-----BEGIN CERTIFICATE-----XXXX-----END CERTIFICATE-----\r\n"`

**Comment by ynbchery** [comment]
@fredwangwang it is in that format if you look at the cf.txt attachment i included in my original post.

**Comment by scottgai** [comment]
Wondering if anyone has an idea to solve or workaround this issue?

**Comment by mcwumbly** [comment]
> I just tried it but om staged-config failed with `--include-credentials` or `-c`

which version of ops manager are you using?

This sounds like [this issue](https://github.com/pivotal-cf/om/issues/145#issuecomment-402488633), which I thought has since been fixed in most patch versions of ops manager:

> it looks like the Ops Manager bug has been fixed. Let's take another look at this and validate things are good on our end.

Perhaps updating ops manager will help in both cases?

**Comment by calebwashburn** [comment]
This format works for me

```
product-properties:
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
        cert_pem: |
          Your cert pem
        private_key_pem: |
           Your private key pem
      name: wildcard
```

**Comment by scottgai** [comment]
@mcwumbly @calebwashburn 
thanks for your comments! 
The following format worked for me

```
product-properties:
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
          cert_pem: "-----BEGIN CERTIFICATE-----*****-----END CERTIFICATE-----\r\n"
          private_key_pem: "-----BEGIN RSA PRIVATE KEY-----*****-----END RSA PRIVATE KEY-----\r\n"
      name:
        configurable: true
        credential: false
        optional: false
        type: string
        value: ha&router
```
