### ISSUE TITLE
Experimental Options - staged-config / config-template - Incomplete Output

### ISSUE THREAD

**Issue by thagh05t** [pivotal-cf/om#202]
I have been automating the installation of tiles through pipelines and am loving the ability to use the experimental features above, but there is a single caveat you all may be aware of.

If there are any plans/nested objects/repeatables in a tile such as the AWS Service Broker or New Relic Broker (anything that has plans that can be customized) they are not added to the configuration template that is spit out by om-cli.

My real question is, is there a workaround for adding these manually that is less trial and error or are there any plans in the near future to fully support the now experimental options?

I would like to help move this along if possible so I can really automate everything to the fullest.

**Comment by mcwumbly** [comment]
hey @thagh05t  could you provide a specific example?

some useful information would be:

1. the tile you're using
2. the command you're running
3. the output you see (or a snippet of it)
4. the output you'd like to or would expect to see instead

thanks!

**Comment by thagh05t** [comment]
The below command  and output is a result of trying to generate a YAML config template. The tile, release, command, and output are all shown.
```
○ → om -v
0.38.0
○ → om config-template -p NewRelic-ServiceBrokerTile-OpsMgr-1.12.9.pivotal
product-properties:
  .properties.allow_paid_service_plans:
    value: false # required
  .properties.app_name:
    value: NewRelicServiceBroker # required
  .properties.app_uri:
    value: newrelic-broker # required
  .properties.app_version:
    value: v1.12.9 # required
  .properties.apply_open_security_group:
    value: false # required
  .properties.newrelic_broker_enable_global_access_to_plans:
    value: true # required
  .properties.nrplans:
    value: null # required
  .properties.org:
    value: NewRelicServiceBroker-service-org # required
  .properties.space:
    value: NewRelicServiceBroker-service-space # required
```

The output is actually pretty solid for this particular tile, but it doesn't outline the optional configuration of the individual nrplans options.

Below is the command and output of an attempt to generate the YAML config of a staged product in my environment. I have made some redactions of course.
```
○ → om -v
0.38.0
○ → om -t TARGET -k -u USERNAME -p PASSWORD staged-config -p newrelic-broker
product-properties:
  .properties.allow_paid_service_plans:
    value: false
  .properties.app_name:
    value: NewRelicServiceBroker
  .properties.app_uri:
    value: newrelic-broker
  .properties.app_version:
    value: v1.12.9
  .properties.apply_open_security_group:
    value: false
  .properties.newrelic_broker_enable_global_access_to_plans:
    value: true
  .properties.nrplans:
    value: null
  .properties.org:
    value: NewRelicServiceBroker-service-org
  .properties.space:
    value: NewRelicServiceBroker-service-space
network-properties:
  network:
    name: services
  other_availability_zones:
  - name: eu-west-1a
  - name: eu-west-1b
  - name: eu-west-1c
  singleton_availability_zone:
    name: eu-west-1a
resource-config:
  delete-all:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
  deploy-all:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
```

Interestingly enough, I am using a previous release on my personal mac (0.37.0) and it outputs the correct information! I have not tested this on a tile as complex as the AWS Service Broker, but it works for the New Relic Broker tile. See below...
```
○ → om -v
0.37.0
○ → om -t https://om.eu.sealedair.io -k -u pigiron -p P1g1r0n@dm1n staged-config -p newrelic-broker
product-properties:
  .properties.allow_paid_service_plans:
    value: false
  .properties.app_name:
    value: NewRelicServiceBroker
  .properties.app_uri:
    value: newrelic-broker
  .properties.app_version:
    value: v1.12.9
  .properties.apply_open_security_group:
    value: false
  .properties.newrelic_broker_enable_global_access_to_plans:
    value: true
  .properties.nrplans:
    value:
    - guid:
        configurable: false
        credential: false
        optional: false
        type: uuid
        value: REDACTED
      licenseKey:
        configurable: false
        credential: false
        optional: false
        type: string
        value: REDACTED
      planDescription:
        configurable: false
        credential: false
        optional: false
        type: string
        value: REDACTED
      planName:
        configurable: false
        credential: false
        optional: false
        type: string
        value: REDACTED
  .properties.org:
    value: NewRelicServiceBroker-service-org
  .properties.space:
    value: NewRelicServiceBroker-service-space
network-properties:
  network:
    name: services
  other_availability_zones:
  - name: eu-west-1a
  - name: eu-west-1b
  - name: eu-west-1c
  singleton_availability_zone:
    name: eu-west-1a
resource-config:
  delete-all:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
  deploy-all:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
```
The last aoutput can actually be used to successfully configure the tile using the om-cli. So, I think there is a bug between 0.37.0 and 0.38.0. I will go ahead and start studying the AWS Service Broker tiles output of the staged-config command now. It is about 2500 lines long though, if you all would like the output and feedback please let me know.

I would also like to add that there are some configurations that are marked as "configurable: false", that are included. From what I have seen this is because there is no way to differentiate between hidden fields such as the above form GUID and fields that are optionally activated. Has this been looked into by chance and is there a plan to clean up the output more? The reason I am asking is because this functionality is essential to my pipelines right now, and likely will be long term as I automate my PCF environment, especially for DR.

**Comment by thagh05t** [comment]
The removal of..
```
configurable: false
credential: false
optional: false
```

..from sub-elements of the output YAML does not happen. For example, in the aws-services tile here is a snippet.

```
.properties.rds_aurora_plans:
    value:
    - CreateDBCluster_BackupRetentionPeriod:
        configurable: false
        credential: false
        optional: false
        type: integer
        value: 1
      CreateDBCluster_Engine:
        configurable: false
        credential: false
        optional: false
        type: string
        value: aurora
      CreateDBCluster_EngineVersion:
        configurable: false
        credential: false
        optional: false
        type: string
        value: 5.6.10a
```

Furthermore, this rds_aurora_plans is not even enabled. There should be some correlation to determine if the fields are even enabled imho. But maybe in a later iteration? Unfurling the data correctly (even if its too much data) so that it can be used to automate the later (re)installation of a tile (such as for DR) is my main goal today.

**Comment by mcwumbly** [comment]
(fyi, you had a username/password exposed in one of your previous comments. i removed it, but you may need to rotate those creds if that was an environment that's important.)

**Comment by mcwumbly** [comment]
@thagh05t - Let's keep this focused on the `staged-config` example and create a separate issue for the `config-template` case if needed. The latter command is a bit less mature, so I think focusing on `staged-config` first makes sense.

If I understand correctly, the main issue you're identifying there in this example is the fact that in `0.38.0`, when you run `om staged-config -p newrelic-broker` you're seeing this:

```
  .properties.nrplans:
    value: null
```

instead of this, which you'd like to see (and are seeing with `0.37.0`:

```
  .properties.nrplans:
    value:
    - guid:
        configurable: false
        credential: false
        optional: false
        type: uuid
        value: REDACTED
      licenseKey:
        configurable: false
        credential: false
        optional: false
        type: string
        value: REDACTED
      planDescription:
        configurable: false
        credential: false
        optional: false
        type: string
        value: REDACTED
      planName:
        configurable: false
        credential: false
        optional: false
        type: string
        value: REDACTED
```

The corresponding property in the New Relic Service Broker tile's metadata is a `collection` type, which looks like this:

```
- configurable: true
  description: New Relic Plans (each plan associated with an RPM acount)
  label: New Relic Service Plans
  name: nrplans
  optional: false
  property_blueprints:
  - description: Name of Plan
    label: Plan Name
    name: planName
    type: string
  - description: Description of Plan
    label: Plan Description
    name: planDescription
    type: string
  - description: Associated license key for the Plan
    label: New Relic License Key
    name: licenseKey
    type: string
  type: collection
```

This pull request we merged from @jtarchie and @fredwangwang is likely related: https://github.com/pivotal-cf/om/pull/173

One of the features in that PR was to address this issue https://github.com/pivotal-cf/om/issues/166 to "filter out properties underneath non-selected selector options from `staged-config`"

Perhaps the redaction there is a little too aggressive.
