### ISSUE TITLE
Include the ability to set errand state in configure product command

### ISSUE THREAD

**Issue by calebwashburn** [pivotal-cf/om#214]
As a consumer I would like to be able to call configure product to also set the errand state instead of having to call additional command `set-errand-state`.  Like resource configuration proposing that another yaml element be added to configure product yaml input to allow setting the state of each errand.  Format would be like the following:

```
errand-config:
  smoke_tests:
    post-deploy-state: enabled
    pre-delete-state: enabled
  push-usage-service:
    post-deploy-state: disabled
    pre-delete-state: disabled
```

This would allow configuration of all aspects of a given product in a single configuration command which is orchestrated by `om` to correct endpoints on Operations Manager.
