### ISSUE TITLE
`staged-config` does not handle selectors whose `value` don't match their `name`

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#226]
When using the `staged-config` on the `p-redis` tile, the YAML file contained a selector property set as:

```yaml
  .properties.small_plan_selector:
    value: Plan Active
```

The implementations of `staged-config` assumes that the `value` of selector is also the the name used in the properties scoping. For example,

```yaml
  .properties.some_selector
    value: small
```

would filter out all properties that did not match the name `.properties.some_selector.small`.

Since the value of the `p-redis` tile, all properties that weren't `.properties.small_plan_selector.Plan Active` were filtered out.

It turns out that the selector property name is not correct. *gasp*

The selector `value` above and the property name differ.

Based on what we seem from the `p-redis` properties, we should be filtering out everything that is not `.properties.small_plan_selector.active`.

I don't know if there is any way to programmatically do with the OM API without actually having the tile metdata.

**Comment by jtarchie** [comment]
It looks like there is no way to programmatically do this.

The OpsMan API returns a payload that looks like this:

```json
".properties.backups_selector": {
"type": "selector",
"value": "S3 Backups",
"optional": false
},

".properties.backups_selector.s3.enable_email_alerts.value": {}
```

We'd need to the `name` of the selected value to be able to do things.

So it would be nice if the OpsMan API returned.

```json
".properties.backups_selector": {
"type": "selector",
"name": "s3",
"value": "S3 Backups",
"optional": false
},

".properties.backups_selector.s3.enable_email_alerts.value": {}
```

**Comment by rafnul** [comment]
Ops Manager 2.2.13 implemented a change to resolve this issue:

https://docs.pivotal.io/pivotalcf/2-2/pcf-release-notes/opsmanager-rn.html#2-2-13

I was able to resolve this with local build by adding a SelectedOption property of type string to staged_products_service.go (yaml selected_option).

Then I dropped into line 98 of staged_config.go, and for reverse compatability, check SelectedOption for empty string, then set selectedProperties[name] to that if not empty, else set it to property.Value.(string)

**Comment by kcboyle** [comment]
The selector issue is being addressed by the Platform Automation team to accommodate a change to the Ops Manager API (change as follows):

For the different combinations that these properties can be set.
* If `option_value` is set, automatically assign the appropriate `value`.

*POST*
```yaml
product-properties:
  .properties.disk_alarm_threshold:
    option_value: 15gb
```

*GET*
```yaml
product-properties:
  .properties.disk_alarm_threshold:
    value: "About 15 GB of RAM"
    option_value: 15gb
```

* If the `value` is set, automatically assign the appropriate `option_value`.

*POST*
```yaml
product-properties:
  .properties.disk_alarm_threshold:
    value: "About 15 GB of RAM"
```

*GET*
```yaml
product-properties:
  .properties.disk_alarm_threshold:
    value: "About 15 GB of RAM"
    option_value: 15gb
```

* If both values are set,
   * and they don't match each other, error.

*POST*
```yaml
product-properties:
  .properties.disk_alarm_threshold:
    value: "About 15 GB of RAM"
    option_value: 100gb
```

Reponse
```
422
errors:
- ... write appropriate message here ...
```
   * and they match each other, save their value.

*POST*
```yaml
product-properties:
  .properties.disk_alarm_threshold:
     value: "About 15 GB of RAM"
     option_value: 15gb
```

*GET*
```yaml
product-properties:
  .properties.disk_alarm_threshold:
    value: "About 15 GB of RAM"
    option_value: 15gb
```


The change in `om` should be able to filter using the new `option_value` key back to OpsManager 2.2, and return some kind of warning/error if it is used in an older version of OpsManager (if the API does not respect unrecognized keys).
