### ISSUE TITLE
Add Configure-authentication config file support

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#246]
Story to unwrap [`configure-authentication`](https://www.pivotaltracker.com/story/show/159974379)

Currently, we have a wrapper around `configure-authentication` to allow the configurations to be passed in using `--config config.yml`. Would like to merge that behavior into `om`.

Proposed changes:
adding a `--config` flag which takes configuration file for auth.

File format: replicate flat flag structure
example:
```yaml
username: 
password: 
decryption-passphrase: 
http-proxy-url: 
https-proxy-url: 
no-proxy: 
```
