### ISSUE TITLE
retrieve errand for `staged-config`

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#261]
`configure-product` is now able to set the errand state for the given product, but its counterpart `staged-config` could not retrive errand.
It makes sense that `staged-config` would output the errand info as well.

Format:
to match the input format of `configure-product`, the errand section should look like:
```yaml
errand-config:
  smoke_tests:
    post-deploy-state: true
    pre-delete-state: default
  push-usage-service:
    post-deploy-state: false
    pre-delete-state: when-changed
```

it is for the use case:
`staged-config` (from one foundation)-> `configure-product` (to another foundation). 

But right now `staged-config` misses `errand` props, so it is helpful that `staged-config` can return that piece of info to enable the migration of errand state.
