### ISSUE TITLE
add `product-name` to the config generated by staged-config 

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#271]
configure-product is able to take `product-name` from the configuration, however, its counterpart staged-config does not output product-name to the config generated.

We want to add the ability to have product-name in the generated config from `staged-config` command.

**Comment by fredwangwang** [comment]
generated config would looks like:

```yaml
---
product-name: cf
product-properties:
......
```
