### ISSUE TITLE
Proposal: migrate properties to top level field in `configure-director` (breaking change)

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#310]
# Problem

We were going to add a new property to `configure-director` for the `dns-configuration`. It would've been a top level key for the configuration file.

Example:

```yaml
dns-configuration: {}
iaas-configuration: {}
resource-configuration: {}
# .... some more ....
```

The top level keys of `iaas_configuration`, `director_configuration`, `dns_configuration`, `security_configuration`, and `syslog_configuration` all map to a [single API endpoint](http://docs.pivotal.io/pivotalcf/2-2/opsman-api/#updating-director-and-iaas-properties-experimental) for director properties. But `om` currently flattens out those properties and mixes them in with other configurations that only map to a single endpoint -- ie `resource-configuration`.

This is not future proofed. When a new key is added to the director properties, we've got to extend `om` to support it.

# Proposed Change

We'd like to change `configure-director` config file to have `properties-configuration`. This value would be the payload passed along to director properties. It would remove the need to combine several top level keys into one payload.

The previous above example configuration would transform to:

```yaml
properties-configuration:
  dns_configuration: {}
  iaas_configuration: {}
  director_configuration: {}
resource-configuration: {}
# .... some more ....
```

# Possible migration path

We could pretty easily ship a command that moves the keys in an existing configuration. It would get uglified, but a lot of these are machine-dumped anyway.
