### ISSUE TITLE
A guid identifier is always causing a "change" to a tile configuraiton

### ISSUE THREAD

**Issue by hjaffan** [pivotal-cf/om#315]
We have a tile that we are configuring using the om cli and we have noticed the following issue:

Even though we have not altered the configuration of the tile, there is a guid that seems to be auto generated by opsman that's causing it to think there is an update.

Here's an example of the guid that is randomly being generated everytime there is a new configuration.

This perticular one is happening when configuring an appdynamics tile version v4.5.556.

I got this based on the diff I made based on the deployed state vs the staged state. 
```
  - deployed: true
    records:
    - properties:
      - deployed: false
        identifier: guid
        value: fa681753-e893-41fb-b2d0-cd7e03999529
      - deployed: false
```

om cli version is 0.44.0 and the opsman version is v2.3-build.194

**Comment by kcboyle** [comment]
@hjaffan in the metadata of the tile you are using, does the collection in question have a `name` identifier? if not, it could potentially be related to this issue: https://github.com/pivotal-cf/om/issues/207

Can you confirm?

**Comment by hjaffan** [comment]
@kcboyle so here's what I see in the metadata file

```
- configurable: true
  description: Appdynamics Controller Information
  label: Appdynamics Service Information
  name: appd_plans
  optional: false
  property_blueprints:
  - label: Plan id
    name: guid
    optional: false
    type: uuid
    unique: true
  - configurable: true
    label: Controller Configuration Name
    name: plan-name
    type: string
  - configurable: true
    label: Controller Configuration Description
    name: plan-description
    type: string
  - configurable: true
    descritption: Controller Account Name
    label: Account Name
    name: account-name
    type: string
  - configurable: true
    description: Access key for the above specified controller account
    label: Account Access Key
    name: account-access-key
    type: string
  - configurable: true
    description: Host name of the controller
    label: Controller Host
    name: host-name
    type: string
  - configurable: true
    description: Controller Port
    label: Controller Port
    name: port
    type: string
  - configurable: true
    default: false
    label: SSL
    name: ssl-enabled
    type: boolean
  type: collection
```

So the collection type does have a name property for that guid. Is this what you meant?
