### ISSUE TITLE
Feature Request - adding/updating vm types that are available to select

### ISSUE THREAD

**Issue by calebwashburn** [pivotal-cf/om#337]
Would like to have the ability to manage custom vm types (https://docs.pivotal.io/pivotalcf/2-4/opsman-api/#overriding-defaults-with-custom-vm-types).  Much like vm_extensions this would be another configuration element that is used by `configure-director` extend the default out of box vm_types that opsmanager ships with.

**Comment by kcboyle** [comment]
@calebwashburn similar to vm_extensions, is this also something that is only configured via the API? or is this a missing UI feature?

**Comment by calebwashburn** [comment]
@kcboyle there is no way to do this in UI

**Comment by kcboyle** [comment]
Thanks for the extra context @calebwashburn. We might not be able to prioritize this for a while, but feel free to submit a PR!

**Comment by jghiloni** [comment]
I've been working on this with @kcboyle and we've determined the following flow will work for `configure-director`:

```
vmtypes-config:
  types:
    - name: vmtype1
      cpu: 1
      ram: 2048
      ephemeral_disk: 10240
```

In this context, the vm type `vmtype1` is added to the list of default vm types. Note that this is _NOT_ default API behavior. If you wish to mimic API behavior exactly, you would do:
```
vmtypes-config:
  custom_only: true
  types:
    - name: vmtype1
      cpu: 1
      ram: 2048
      ephemeral_disk: 10240
```

This will behave as the API does and eliminate all existing VM types.
