### ISSUE TITLE
Delete VM Extensions

### ISSUE THREAD

**Issue by dawu415** [pivotal-cf/om#355]
Hello,

Would like to request for an om cli feature to delete a VM extension.  The use case for this is where a VM extension is no longer used or needs to be renamed.  

This is supported by ops manager via curl calls. 
https://docs.pivotal.io/pivotalcf/2-2/customizing/custom-vm-extensions.html#delete-vm-exension

**Comment by zachgersh** [comment]
This kind of goes into the discussion we were having about removing `create-vm-extensions` command all together. Maybe all vm-extension management is done via `om curl` and we don't add any of these commands?

what do you think @kcboyle / @jtarchie

**Comment by xyloman** [comment]
A vm-extensions command could be really useful if it were to ensure state such as delete extensions no longer provided, create those that are new and update those that have changed in one command.  This makes it way easier to automate since you are defining a desired state.  Using curl and specific CRUD operations actually make automating the configuration more difficult.

**Comment by aegershman** [comment]
I draw inspiration from [how `cf-mgmt` does config](https://github.com/pivotalservices/cf-mgmt), and allows you to declaratively specify what you want & it'll handle the resolution of it. As an example in `cf-mgmt` you can configure...

```yml
# myOrgDefinition.yml
private-domains:
- flarp.biz
- foo.gov
- buzz.xxx
enable-remove-private-domains: true # <-- point of interest
```

Point of interest in `enable-remove-private-domains`, which means `cf-mgmt` would remove anything which _isn't_ configured within `myOrgDefinition.yml`. (If you had this to `false` and you had some `private-domain` configured against your CF org that wasn't defined in `myOrgDefinition.yml`, it would _not_ be removed)

The point of all this is to say doing these things imperatively via `curl` would be harder, because now the automation (see: `bash` script) is responsible for performing a diff of all the `vm_extensions` which needs to be applied and which ones need to be removed. The closer things can move to a purely declarative configuration model which handles more of the logic of "what should be here" vs. "what should be deleted", the better & easier it will be to create, maintain, and standardize automation.

I realize I might be making assumptions about features that don't exist, but just sharing thoughts on what the ideal state could be (from my point of view at least-- I'm often wrong, so go figure 😉)

thoughts?

**Comment by kcboyle** [comment]
So `configure-director` does allow for the creation and deletion of vm_extensions (and since `configure-director` doesn't care if you have a full config or not, you could, in theory, use it only to create and delete vm_extensions) via use of the config file:
```
vmextensions-configuration:
- name: a_vm_extension
  cloud_properties:
    source_dest_check: false
- name: another_vm_extension
  cloud_properties:
    foo: bar
```

If the extension does not exist, `configure-director` will create the extension ([function](https://github.com/pivotal-cf/om/blob/master/commands/configure_director.go#L374), [call](https://github.com/pivotal-cf/om/blob/master/commands/configure_director.go#L448)). If the vm_extensions list does not include an extension already present, it will delete the extensions from the director ([function](https://github.com/pivotal-cf/om/blob/master/commands/configure_director.go#L427), [call](https://github.com/pivotal-cf/om/blob/master/commands/configure_director.go#L453)). 

the vm_extension functionality in `configure-director` is more fully featured than just `create-vm-extension` in this way, and in that you can create as many or as few extensions as you need for your foundation.

So I would agree with @zachgersh that perhaps the `create-vm-extension` command is unnecessary, but because we have the feature implemented elsewhere. 

@aegershman brings up a good point, however. Perhaps `configure-director` needs a failsafe for the delete such as `enable-vm-extensions-delete: true|false`, as there is no way to prevent the delete if it is not present in your config (it's a heavy-handed replace). 

this feature is only documented in the [om docs for configure-director](https://github.com/pivotal-cf/om/tree/master/docs/configure-director), and we don't think that this is a widely known feature of `configure-director`. Does the command do what is needed for y'all (@aegershman , @dawu415 @xyloman @zachgersh )? 

From our perspective, rather than creating the `delete-vm-extension` command, we could add in a failsafe to `configure-director` to add more flexibility around vm-extension management.

**Comment by kcboyle** [comment]
A comment from @nbconklin: 
Rather than the `enable-vm-extensions-delete` option, what if we had a default check (similar to the check in `delete-installation`) that would verify before delete each vm-extension in the `vm-extensions` block? This could then be bypassed by a `--force` flag.  Any thoughts on this and the above?

@zachgersh @aegershman @dawu415 @xyloman

**Comment by kcboyle** [comment]
@zachgersh @aegershman @dawu415 @xyloman 

Just giving a kindly reminder to assess your thoughts on the above before we decide to do anything further for this

**Comment by kcboyle** [comment]
@zachgersh @aegershman @dawu415 @xyloman 

We're going to throw a `PR Welcome` on this issue. 
We would like `configure-director` to have a `--force-vm-extensions` flag that will delete any vm_extensions not defined in your configuration.
By default, if the `vm_extensions` block is defined, we will do a check to verify whether you would like to delete any extensions found in OpsMan, but not found in the config. 

If `vm_extensions` is not defined, it will not attempt to add/delete any `vm_extensions`

**Comment by kcboyle** [comment]
Additional note for this issue:
the behavior now will delete vm extensions if "[]" is provided. (this is returned from `staged-director-config` as `vm_extensions: []`)
1. `staged-director-config` behavior should stay the same
1. `vm_extensions: []` in `configure-director` should _not_ delete `vm_extensions`
1. vm_extensions should only delete if `--force-vm-extensions` is provided, otherwise it will simply not add any any extensions.

some use cases -- PR, please have a unit test for the following:
1. with the following director-config, `another_vm_extension` exists on OpsMan
    ```yaml
    vmextensions-configuration:
    - name: a_vm_extension
      cloud_properties:
        source_dest_check: false
    ```
    **`configure-director --force-vm-extension` should**:
    DELETE another_vm_extension
    ADD a_vm_extension

1. with the following director-config, no extensions exist on OpsMan
    ```yaml
    vmextensions-configuration:
    - name: a_vm_extension
      cloud_properties:
        source_dest_check: false
    - name: another_vm_extension
      cloud_properties:
        source_dest_check: false
    ```
    **`configure-director --force-vm-extension` should**:
    ADD another_vm_extension
    ADD a_vm_extension

1. with the following director-config, `a_vm_extension` and `another_vm_extension` exist on OpsMan
    ```yaml
    vmextensions-configuration: []
    ```
    **`configure-director --force-vm-extension` should**:
    DELETE another_vm_extension
    DELETE a_vm_extension

1. with the following director-config, `a_vm_extension` and `another_vm_extension` exist on OpsMan
    ```yaml
    vmextensions-configuration: []
    ```
    **`configure-director` should**:
    do nothing with vm_extensions

1. with the following director-config, `another_vm_extension` exists on OpsMan
    ```yaml
    vmextensions-configuration:
    - name: a_vm_extension
      cloud_properties:
        source_dest_check: false
    ```
    **`configure-director` should**:
      ADD a_vm_extension
