### ISSUE TITLE
`om staged-config` may not generate all configured elements

### ISSUE THREAD

**Issue by brightzheng100** [pivotal-cf/om#364]
While using `om staged-config` for some products, like `newrelic-broker`, some dynamically generated elements (e.g. the plans) couldn't be generated properly -- some with `null` values and some were simply missing.

ENV:
- `om` cli: v0.54.0
- OpsMan: v2.3.11

The one generated:
```
product-name: newrelic-broker
product-properties:
  .properties.allow_paid_service_plans:
    value: false
  .properties.apply_open_security_group:
    value: false
  .properties.newrelic_broker_enable_global_access_to_plans:
    value: true
  .properties.nrplans:
    value:
    - insightsInsertKey: null
      orgs: null
      planOldGuid: null
      rpmAccountId: null
  .properties.org:
    value: NewRelicServiceBroker-service-org
  .properties.space:
    value: NewRelicServiceBroker-service-space
```

The right config (after manually detecting and adding up):
```
product-name: newrelic-broker
product-properties:
  .properties.allow_paid_service_plans:
    value: false
  .properties.apply_open_security_group:
    value: false
  .properties.newrelic_broker_enable_global_access_to_plans:
    value: true
  .properties.nrplans:
    value:
    - planName: nrtrialplan
      planDescription: testplan
      licenseKey: 0b10d7fb14cd4decdea417adad093eacee7f9466
      insightsInsertKey: ""
      orgs: ""
      planOldGuid: ""
      rpmAccountId: ""
 .properties.org:
    value: NewRelicServiceBroker-service-org
  .properties.space:
    value: NewRelicServiceBroker-service-space
```

So you can see the `.properties.nrplans` part is wrongly generated.
