### ISSUE TITLE
`om staged-director-config` does not handle `director_configuration` for OpsMan 2.3.x

### ISSUE THREAD

**Issue by jrussett** [pivotal-cf/om#372]
## Summary
When using `om 1.0.0+` and  running `staged-director-config` against a foundation with OpsMan `2.3.*`, `om` does not return the expected value for configuration hash key `director_configuration`, and instead returns an empty array.

## Expected Result
The returned yaml object to include a hash key, `/properties-configuration/director_configuration`, with child keys, e.g.:
```
bc+jr $ ./om-0.57.0 -v
0.57.0
bc+jr $ ./om-0.57.0 -k staged-director-config
az-configuration: []
network-assignment:
  other_availability_zones: []
networks-configuration:
  icmp_checks_enabled: true
  networks: []
properties-configuration:
  director_configuration:
    allow_legacy_agents: true
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    excluded_recursors: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: ""
    post_deploy_enabled: false
    resurrector_enabled: false
    retry_bosh_deploys: false
    skip_director_drain: true
  dns_configuration:
    handlers: []
  security_configuration:
    generate_vm_passwords: true
  syslog_configuration:
    enabled: false
...
```

## Actual Result
Key, `/properties-configuration/director_configuration`, is mapped to an empty array:
```
bc+jr $ ./om-1.0.0 -v
1.0.0
bc+jr $ ./om-1.0.0 -k staged-director-config
az-configuration: []
network-assignment:
  other_availability_zones: []
networks-configuration:
  icmp_checks_enabled: true
  networks: []
properties-configuration:
  director_configuration: []
  dns_configuration: []
  security_configuration: {}
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
vmextensions-configuration: []
```

## Versions Involved:
OpsMan: `v2.3-build.313`
`om`: `0.57.0`, `1.0.0`, `1.1.0`

#### Addition of `--include-placeholders --no-redact` parameters does not affect the outcome:
```
bc+jr $ ./om-1.0.0 -v
1.0.0
bc+jr $ ./om-1.0.0 -k staged-director-config --include-placeholders --no-redact
az-configuration: []
iaas-configurations:
- bosh_disk_path: ((iaas-configurations_0_bosh_disk_path))
  bosh_template_folder: ((iaas-configurations_0_bosh_template_folder))
  bosh_vm_folder: ((iaas-configurations_0_bosh_vm_folder))
  ...
  vcenter_password: ((iaas-configurations_0_vcenter_password))
  vcenter_username: ((iaas-configurations_0_vcenter_username))
network-assignment:
  other_availability_zones: []
networks-configuration:
  icmp_checks_enabled: true
  networks: []
properties-configuration:
  director_configuration: []
  dns_configuration: []
  security_configuration:
    generate_vm_passwords: ((properties-configuration_security_configuration_generate_vm_passwords))
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
vmextensions-configuration: []
```

#### `om 1.1.0` has identical output:
```
bc+jr $ ./om-1.1.0 -v
1.1.0
bc+jr $ ./om-1.1.0 -k staged-director-config
az-configuration: []
network-assignment:
  other_availability_zones: []
networks-configuration:
  icmp_checks_enabled: true
  networks: []
properties-configuration:
  director_configuration: []
  dns_configuration: []
  security_configuration: {}
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
vmextensions-configuration: []
```
