### ISSUE TITLE
Non-configurable properties cannot be configured

### ISSUE THREAD

**Issue by ramonskie** [pivotal-cf/om#392]
when running the following comand to generate the tile config files

`om config-template --pivnet-api-token=xxxxx  --pivnet-product-slug=elastic-runtime --product-version=2.5.4 --product-file-glob='srt*.pivotal' --output-directory test`

the following file is created `features/credhub_database-external.yml`
with contains this non-configurable property

```
 - type: replace
   path: /product-properties/.properties.credhub_database.external.require_tls?
   value:
     value: ((credhub_database/external/require_tls))
```

**Comment by jtarchie** [comment]
Can you clarify your expectation here or an error message that you experienced?

I can see from the tile metadata the property is not configurable, as it does not explicitly set `configurable: true`.

**Comment by nbconklin** [comment]
Thanks for sharing - we have some upcoming work to make improvements to the config-template. Would like to circle back with you when we've done that - happy to hear more context from you in the meantime. Thank you.

**Comment by ramonskie** [comment]
the problem is when. this entry is in the yml file. and you try to configure the the product. it will fail,
with the error above.
i don't how to clarify this any further. :)

**Comment by jtarchie** [comment]
This should be fixed in https://github.com/pivotal-cf/om/commit/bb4d7e14613d801245a3632f5ad9cc9d89ae5610, released in v2.0.0.

I ran the command, above, and this is the output.

```yaml
○ → cat test/cf/2.5.4/features/credhub_database-external.yml
- type: replace
  path: /product-properties/.properties.credhub_database?
  value:
    value: external
    selected_option: external
- type: replace
  path: /product-properties/.properties.credhub_database.external.host?
  value:
    value: ((credhub_database/external/host))
- type: replace
  path: /product-properties/.properties.credhub_database.external.port?
  value:
    value: ((credhub_database/external/port))
- type: replace
  path: /product-properties/.properties.credhub_database.external.username?
  value:
    value: ((credhub_database/external/username))
- type: replace
  path: /product-properties/.properties.credhub_database.external.password?
  value:
    value:
      secret: ((credhub_database/external/password))
- type: replace
  path: /product-properties/.properties.credhub_database.external.tls_ca?
  value:
    value: ((credhub_database/external/tls_ca))
```
