### ISSUE TITLE
Setting `additional_vm_extensions` to `[]` should erase all extensions.

### ISSUE THREAD

**Issue by jghiloni** [pivotal-cf/om#400]
There's currently no way to remove all VM Extensions from a VM using the `resource-config` block of a config yaml. I would expect setting `additional_vm_extensions: []` would have that effect, but it's the same effect as not setting the key at all.

**Comment by nbconklin** [comment]
@jghiloni  

I believe we intentionally would not delete `vm_extensions` when empty because there was a use case to allow additions without having to redefine all of them. Using the `--force` as described in #355 would allow for deletion of the extensions.

#355- would this type of solution work?

**Comment by nbconklin** [comment]
@jghiloni ping!

**Comment by jghiloni** [comment]
I think a `--force` flag could be useful, yes, especially if we updated the `configure-director` task to provide that as an option via env var that could control whether or not it's there.

**Comment by jtarchie** [comment]
@jghiloni is it good for us to close this issue, in favor of #355?

**Comment by jghiloni** [comment]
I'm reopening this due to a misunderstanding between this and #355. In that issue, they want the ability to delete VM extensions from the director/the generated runtime config. In this issue, I want to be able to remove existing VM extensions from the list of extensions attached to an instance group.

**Comment by kcboyle** [comment]
Could we have similar unit tests to those described in #355 for this as well?

Functionality for deleting the vm_extensions for a particular product instance_group should only delete if `--force-vm-extensions` flag is defined.

using `backup-restore` for simplicity
1. with the following product-config, `another_vm_extension` exists for backup-restore on OpsMan
    ```yaml
    resource-config:
      backup_restore:
        instances: 0
        additional_vm_extensions:
        - a_vm_extension
    ```
    **`configure-product --force-vm-extensions` should**:
    DELETE another_vm_extension
    ADD a_vm_extension

1. with the following product-config, no extensions exist for backup-restore on OpsMan
    ```yaml
    resource-config:
      backup_restore:
        instances: 0
        additional_vm_extensions:
        - a_vm_extensions
        - another_vm_extension
    ```
    **`configure-product --force-vm-extensions` should**:
    ADD another_vm_extension
    ADD a_vm_extension

1. with the following product-config, `a_vm_extension` and `another_vm_extension` exist for backup-restore on OpsMan
    ```yaml
    resource-config:
      backup_restore:
        instances: 0
        additional_vm_extensions: []
    ```
    **`configure-product --force-vm-extensions` should**:
    DELETE another_vm_extension
    DELETE a_vm_extension

1. with the following product-config, `a_vm_extension` and `another_vm_extension` exist for backup-restore on OpsMan
    ```yaml
    backup_restore:
      instances: 0
      additional_vm_extensions: []
    ```
    **`configure-product` should**:
    do nothing with vm_extensions

1. with the following product-config, `another_vm_extension` exists for backup-restore on OpsMan
    ```yaml
    resource-config:
      backup_restore:
        instances: 0
        additional_vm_extensions:
        - a_vm_extension
    ```
    **`configure-product` should**:
      ADD a_vm_extension
