### ISSUE TITLE
configure-ops-manager command - makes configuring Ops Manager settings as easy as configuring BOSH Director settings

### ISSUE THREAD

**Issue by mrdavidlaing** [pivotal-cf/om#454]
Ops Manager itself has a number of "non authentication" settings that should be managed when automating foundation setup - https://docs.pivotal.io/platform/ops-manager/2-7/pcf-interface.html#settings - including:

1.  Syslog
2. Banner

Whilst it is possible to configure these using `om curl`; a helper command would make this easier and more discoverable.

In terms of implementation; behaviour similar to [`om configure-director`](https://github.com/pivotal-cf/om/blob/master/docs/configure-director/README.md) would be ideal; eg:

```
om configure-ops-manager --config ops-manager-config.yml --vars-file vars.yml
```

where `ops-manager-config.yml` would look something like:

```yaml
---
customer-banners:
  ui_banner_contents: "This is a custom UI Banner",
  ssh_banner_contents: "This is a custom SSH banner"
syslog:
  enabled: true
  address: "logs5.papertrailapp.com"
  port: 12345
  transport_protocol: "tcp"
  tls_enabled: false
  ssl_ca_certificate: ((my_company_ca))
  permitted_peer: null,
  queue_size: 10003,
  forward_debug_logs: false,
  custom_rsyslog_configuration: "if ($msg contains \"DEBUG\") then stop"
```
