### ISSUE TITLE
Multiple om targets specified in the same env file

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/om#460]
One more idea to tack onto this heap here: https://github.com/pivotal-cf/om/issues/385

Consider allowing multiple foundation targets within the same `env.yml`, so foundation targets could be defined in a single `env.yml` and targeted with an argument such as `om --env myenv.yml -t aws-us-west-2-sandbox` (or since `-t` is taken, maybe `-a` for `--alias`?)

Where an `env.yml` could be either a single foundation (how it is currently), or a list of targets with an `alias:` key, e.g.

current: 

```yml
---
target: https://xyz.io
connect-timeout: 30         
request-timeout: 1800      
skip-ssl-validation: false   
username: foo
password: bar
```

idea:

```yml
---
targets:
- alias: xyz 
  target: https://xyz.io
  connect-timeout: 30         
  request-timeout: 1800      
  skip-ssl-validation: false   
  username: foo
  password: bar
- alias: abc
  target: https://abc.biz
  connect-timeout: 2
  request-timeout: 7
  skip-ssl-validation: true
  client-id: aaaah
  client-secret: shhhhh
```

then specified as `om --env env.yml --alias xyz [rest of commands...]`

thoughts? thanks again, and apologies for taking up time/space with the github issues as a place to plop ideas, feel free to close whenever 👌
