### ISSUE TITLE
Download Product from S3 compatible blobstore fails with ' BadRequest: Bad Request' error

### ISSUE THREAD

**Issue by shchoube** [pivotal-cf/om#461]
Download Product from S3 compatible blobstore fails with ' BadRequest: Bad Request' error. We are using IBM cleversafe. We are also able to download the product files in concourse if we define it as resource. for example:

```yaml
- name: ops-manager-image
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    secret_access_key: ((s3_secret_access_key))
    bucket: ((s3_bucket))
    endpoint: ((s3_endpoint))
    regexp: ops-manager/pcf-vsphere-2.4.(.*).ova
    skip_ssl_verification: true
    use_v2_signing: true
```

However, i we OM to download the product, it fails with bad request. I have tried multiple times. still no go:

> --source "s3" \
> --output-directory "downloaded-files" \
> --pivnet-product-slug "ops-manager" \
> --product-version "2.6.13" \
> --pivnet-file-glob ops-manager-vsphere-*.ova \
> --s3-endpoint "s3-endpoint" \
> --s3-bucket "s3-bucket" \
> --s3-product-path "ops-manager/" \
> --s3-region-name "region" \
> --s3-secret-access-key "somesecretkey" \
> --s3-access-key-id  "someaccesskeyid" \
> --s3-enable-v2-signing "false" \
> --s3-disable-ssl "false"

error
attempting to download the file ops-manager/[ops-manager,2.6.13]ops-manager-vsphere-2.6.13-build.233.ova from source s3
could not execute "download-product": could not download product: getItem, getting the object: BadRequest: Bad Request
        status code: 400, request id: 48569e04-cc6b-4956-85ff-b3644c0c3c3d, host id:
