### ISSUE TITLE
add a configure-opsman task to `om` - support ssl-certificate

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#474]
There are various configurations in the Ops Manager UI settings that can be accessed using the API:
ssl-certificate - /api/v0/settings/ssl_certificate
pivnet api token - /api/v0/settings/pivotal_network_settings
role-based access controls - /api/v0/settings/rbac
custom banner - /api/v0/settings/banner
custom syslog settings - /api/v0/settings/syslog

We should begin to add support for these settings in a new command.

Proposal:
- add a new `configure-opsman` command
- this command should add support for rotating the ssl-certificate, and be extensible to include the other endpoints _eventually_
- command should take a config file
  - config file should be able to have non-command-relevant keys
    example(top level config key for this command is up for debate):
      ```yaml
      unrelevant-key:
        nested-key:
          key: value
      opsman-configuration:
        ssl-configuration:
          private-key: some-key
          certificate-pem: some-cert
      ```
- deprecate `update-ssl-certificate` command
- update changelog

Will create follow-up stories to support each additional endpoint
