### ISSUE TITLE
`configure-opsman` should support update of rbac

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#476]
Extension of #474 

extend the `configure-opsman` command to allow setting the role-based access controls.

Relevant endpoint:  /api/v0/settings/rbac

An example addition to the config file: 
```
rbac-settings:
  rbac_saml_admin_group: example_group_name
  rbac_saml_groups_attribute: example_attribute_name
```

Add a test for LDAP, as this is supported:
```
rbac-settings:
  ldap_rbac_admin_group_name: "cn=opsmgradmins,ou=groups,dc=mycompany,dc=com"
```

There should also a test that prevents SAML and LDAP values _both_ being provided
The following example should ERROR if provided:
```
rbac-settings:
  rbac_saml_admin_group: example_group_name
  rbac_saml_groups_attribute: example_attribute_name
  ldap_rbac_admin_group_name: "cn=opsmgradmins,ou=groups,dc=mycompany,dc=com"
``` 

Requirements:
1. Should be able to set independently from other endpoints
1. If top-level key is not provided, does not call the API
1. update example config in docs and indicate new support https://github.com/pivotal-cf/om/blob/master/docsgenerator/templates/configure-opsman/ADDITIONAL_INFO.md 
1. Docs generator should be run to reflect the docs changes
1. update changelog
