### ISSUE TITLE
`config-template` incorrectly parameterizes some nested secrets

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#483]
## Steps to reproduce:
For the Spring Cloud Data Flow for VMware Tanzu (p-dataflow) tile:
1. Run: `om config-template --file-glob *.pivotal --pivnet-api-token <pivnet_token> --pivnet-product-slug p-dataflow --output-directory dataflow --product-version 1.6.6`
1. upload and stage tile to ops manager manually, or run 
    ```
    om --env env.yml upload-product -p p-dataflow-1.6.6.pivotal
    om --env env.yml stage-product -p p-dataflow -v 1.6.6
    ```
1. Run: `om --env env.yml configure-product --config product.yml --vars-file resource-vars.yml --vars-file default-vars.yml --vars-file required-vars.yml --vars-file errand-vars.yml`

The following error occurs:
```
configuring p-dataflow...
setting up network
finished setting up network
setting properties
could not execute "configure-product": failed to configure product: request failed: unexpected response from /api/v0/staged/products/p-dataflow-665b2028692415d425bb/properties:
HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Wed, 18 Mar 2020 20:49:18 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
Server: Ops Manager
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 3154ae58-7b8a-48c8-b265-0da6b1de4b7b
X-Runtime: 0.075909
X-Xss-Protection: 1; mode=block

43
{"errors":{"base":["undefined method `each' for \"pass\":String"]}}
0
```

## Workarounds:
If using If you're using `prepare-tasks-with-secrets` from [platform automation](docs.pivotal.io/platform-automation), you can store the value in credhub as a `value` type with JSON (`credhub set -n maven_repositories_0_password -t value -v '{"secret": "pass"}'`), so the variable will be read into `om` like so:
```
OM_VARS_ENV=VARS VARS_maven_repositories_0_password='{"secret": "pass"}' om --env env.yml configure-product --config product.yml --vars-file resource-vars.yml --vars-file default-vars.yml --vars-file required-vars.yml --vars-file errand-vars.yml
```
alternatively, it can be stored in the pre-created `required-vars.yml` file like this:
```
maven_repositories_0_password:
  secret: pass
```

## Additional Information
`om config-template` is returning the following in `product.yml` for p-dataflow:
```
.properties.maven_repositories:
  value:
  - key: spring
    password: ((password))
    url: https://repo.spring.io/libs-release
    username: username
```

when it _should_ be returning:
```
.properties.maven_repositories:
  value:
  - key: spring
    password: 
      secret: ((password))
    url: https://repo.spring.io/libs-release
    username: username
```

This appears handled correctly in the ops files for this product:
```
- type: replace
  path: /product-properties/.properties.maven_repositories?
  value:
    value:
    - key: ((maven_repositories_0_key))
      password:
        secret: ((maven_repositories_0_password))
      url: ((maven_repositories_0_url))
      username: ((maven_repositories_0_username))
    - key: ((maven_repositories_1_key))
      password:
        secret: ((maven_repositories_1_password))
      url: ((maven_repositories_1_url))
      username: ((maven_repositories_1_username))
```

## Expectation
```
om --env env.yml configure-product --config product.yml --vars-file resource-vars.yml --vars-file default-vars.yml --vars-file required-vars.yml --vars-file errand-vars.yml
``` 
should configure the product without error or manual editing of `product.yml`
