### ISSUE TITLE
How can i generate the  PKS API Certificate and private key through the OM cli.

### ISSUE THREAD

**Issue by dilipk8** [pivotal-cf/om#493]
I'm using OM CLI 4.5.0. I was unable to use :

```yaml
generate_cert_domains: ["*.((pkstest))"]
    value:
      cert_pem:
      private_key_pem:
```

How can i generate the  PKS API Certificate and private key through the OM cli.
Would it work or is this not possible.?
