### ISSUE TITLE
Can `apply-changes` flags be set via config file?

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#494]
Follow up from a comment in #428

Many commands allow command line flags to be passed via a config file. In the case of `apply-changes`, the `--config` flag actually refers to a config file with errand configuration. 

Could we extend the functionality of `--config` to allow other flags to be set in the config file? Or perhaps we should introduce the concept of `--flags` to the command?

Would like to discuss alternatives

From @aegershman 
> Hey @kcboyle okay real quick, sorry to append this to the same github issue I can create another one, but quick idea:
> 
> [on tasks such as `apply-changes` there are certain envvars which can be set like this:](https://docs.pivotal.io/platform-automation/develop/tasks.html#stage-configure-apply)
> 
> ```shell
>   ALLOW_PENDING_CHANGES: false
>   # - Optional
>   # - If false, will fail if there are pending changes in OpsMan
> 
>   RECREATE: false
>   # - Optional
>   # - If true, will recreate the vms for the product
>   # - If true, will also recreate the director vm if there are changes
> 
>   IGNORE_WARNINGS: false
>   # - Optional
>   # - If true, will not fail when verifiers have warnings,
>   #   it will still fail for any errors.
>   # - This is not recommended unless unless the warning failure(s)
>   #   are well understood.
> ```
> 
> Those are valuable flags, though they're set as envvars "statically" and can only be changed/set using `fly`, rather than dynamically reading them from a file in git.
> 
> Any thoughts on making configuration switches like that available to be set in a file as well? E.g. imagine `features.yml` or `options.yml` or `flags.yml` or `switches.yml` or `command-flags.yml`, I have no idea what to actually call it, but it'd be a file that has those same kinds of flags set via task envvars except parameterized as code, example:
> 
> ```yaml
> # flags.yml
> recreate: true
> allow-pending-changes: false
> ignore-warnings: false
> ```
> 
> then have the `flags.yml` be able to be passed in for commands such as `om apply-changes [...] --flags=/some/product/and/foundation/path/here/flags.yml`?
> 
> To be honest this is something I was going to do regardless for how we pass `--recreate` now that we're on 2.9.x+, but just hadn't gotten to it or evaluated it yet 😬
> 
> Just a thought, I can absolutely create this as a separate issue.
> 
> regardless, thanks a ton to you all as well, thanks for your time!

Reply from @kcboyle:
> Hmmmm I can definitely see the use case for the `recreate` and `allow-pending-changes` flags. (though in the case of SCA, `ALLOW_PENDING_CHANGES: true` seems like it would be undesired in the majority of cases)
> 
> I have concerns about `ignore-warnings` being a passable flag. We've been very defensive about how you can set that flag (and only recently added it because there are a few warnings in ops man that do not disappear even if you disable the verifier). if we could pass those in via a file, that _would_ be an `om` change though, not just a change to platform automation.
> 
> I'm not sure how I feel about passing in the flags via a `--flags` flag though. for other commands, we got away with it by allowing a config file (or an `--env` file in the case of the global flags). It just feels...strange?..to have a flag for a command called `flags` that accepts a file.

**Comment by kcboyle** [comment]
@aegershman in a pipeline, could you also just have a separate job with those flags set as desired that is only run when (say recreate) is desired? Can we discuss the pros/cons of that particular workflow? 

ie
```
- task: apply-product-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-changes.yml
    input_mapping:
      env: configuration
    params:
      ENV_FILE: foundations/config/env.yml
- task: recreate-all-vms
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-changes.yml
    input_mapping:
      env: configuration
    params:
      ENV_FILE: foundations/config/env.yml
      RECREATE: true
```
