### ISSUE TITLE
configure-product fails to find the property that is not defined in the previous version of the product

### ISSUE THREAD

**Issue by mariash** [pivotal-cf/om#514]
`configure-product` is failing to associate guids for the property that does not exist in the previous version of the product but is introduced in the new version of the product.

**Steps to reproduce**:

1. Deploy a product that does not have a property configured (TAS 2.6)
2. Upload and stage a product that contains the property and migration (TAS 2.7)
3. Run `configure-product` command:

```
om --target "OPSMAN_TARGET" --skip-ssl-validation configure-product --config "PATH_TO_PRODUCT_CONFIG"
```
where PATH_TO_PRODUCT contains the following configuration for property:
```
  .properties.credhub_internal_provider_keys:
    value:
    - key:
        secret: some-secret
      name: Key
      primary: true
```
4. See that it fails with error:

```
2020/09/01 06:35:54 could not execute "configure-product": failed to configure product: failed to associate guids for property ".properties.credhub_internal_provider_keys" because:
request failed: unexpected response from /api/v0/deployed/products/cf-6bdb4038d37667f9f424/credentials/.properties.credhub_internal_provider_keys[0].key:
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 01 Sep 2020 06:35:54 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
Server: Ops Manager
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 26f79fb5-66a3-44ee-8e56-9de2814f9a07
X-Runtime: 0.114048
X-Xss-Protection: 1; mode=block
```

TAS 2.7 has a migration that introduces this property. The property is of type `collection`.

```
- name: credhub_internal_provider_keys
  type: collection
  configurable: true
  property_blueprints:
  - name: name
    type: string
    configurable: true
  - name: key
    type: secret
    configurable: true
```

@jtarchie @ystros @anEXPer
