### ISSUE TITLE
GCP OpsManager creation can handle configuration of `hostname`

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#531]
When creating an OpsManager VM on GCP, I'd like to be able to configure the [hostname](https://cloud.google.com/compute/docs/instances/custom-hostname-vm).

Via the OpsManager config file, a new attribute could be added for this,

```yaml
opsman-configuration:
  gcp:
    hostname: some.custom.hostname
    boot_disk_size: 100
    custom_cpu: 4
    custom_memory: 16
    gcp_service_account: ((service_account_key))
    project: ((project))
    public_ip: ((ops_manager_public_ip))
    region: ((region))
    ssh_public_key: ((ops_manager_ssh_public_key))
    tags: ((ops_manager_tags))
    vm_name: ((environment_name))-ops-manager-vm
    vpc_subnet: ((management_subnet_name))
    zone: ((availability_zones.0))
```

This would be implemented by updating the `gcloud compute instances create` invocation with [hostname](https://cloud.google.com/sdk/gcloud/reference/compute/instances/create#--hostname).

Tasks:
* [ ] validation on the hostname
* [ ] validate hostname can actually be used
