### ISSUE TITLE
TAS/CF installation fails on task 193 with NoCredentialProviders error.

### ISSUE THREAD

**Issue by kgyovai** [pivotal-cf/om#546]
# Overview
Installing the TAS runtime (product details below) fails with an error of `NoCredentialProviders: no valid providers in chain. Deprecated.`.

## Products
![image](https://user-images.githubusercontent.com/10728023/120491576-59d40300-c387-11eb-9623-433cb6f3b7e6.png)

`om` version: 7.2.0 

## Installation Steps
```
  om configure-product \
    --config=$configFile \
    --vars-file=$varsFile
```

```
  om apply-changes \
    --product-name cf
```

## Attempted Workarounds
* I have attempted to configure both BOSH and TAS with AWS IAM instance profiles __and__ access keys.
* I am using external blobstores (S3 buckets).

## TAS Blobstore Config
```yaml
  .properties.system_blobstore:
    selected_option: external
    value: external
  .properties.system_blobstore.external.access_key:
    value: ((tanzu_ops_user_access_key))
  .properties.system_blobstore.external.buildpacks_bucket:
    value: ((s3_bucket_name_buildpacks))
  .properties.system_blobstore.external.droplets_bucket:
    value: ((s3_bucket_name_droplets))
  .properties.system_blobstore.external.encryption:
    value: true
  .properties.system_blobstore.external.endpoint:
    value: https://s3.us-east-2.amazonaws.com
  .properties.system_blobstore.external.iam_instance_profile_authentication:
    value: false
  .properties.system_blobstore.external.packages_bucket:
    value: ((s3_bucket_name_packages))
  .properties.system_blobstore.external.path_style_s3_urls:
    value: false
  .properties.system_blobstore.external.region:
    value: us-east-2
  .properties.system_blobstore.external.resources_bucket:
    value: ((s3_bucket_name_resources))
  .properties.system_blobstore.external.secret_key:
    value:
      secret: ((tanzu_ops_user_secret_key))
```
## BOSH IaaS Config
```yaml
  iaas_configuration:
    access_type: keys
    access_key_id: ((tanzu_ops_user_access_key))
    secret_access_key: ((tanzu_ops_user_secret_key))
```

## Detailed Error Message
```
 Expected task '193' to succeed but state is 'error'
 '
Task 193 | 13:12:21 | Error: Unable to render instance groups for deployment. Errors are:
 Failed to download S3 object, code 1, output: '', error: '2021/06/02 13:11:57 performing operation get: NoCredentialProviders: no valid providers in chain. Deprecated.
 For verbose messaging see aws.Config.CredentialsChainVerboseErrors
 '
 Failed to download S3 object, code 1, output: '', error: '2021/06/02 13:12:17 performing operation get: NoCredentialProviders: no valid providers in chain. Deprecated.
 For verbose messaging see aws.Config.CredentialsChainVerboseErrors
 '
 Failed to download S3 object, code 1, output: '', error: '2021/06/02 13:12:18 performing operation get: NoCredentialProviders: no valid providers in chain. Deprecated.
 For verbose messaging see aws.Config.CredentialsChainVerboseErrors
 '
 Failed to download S3 object, code 1, output: '', error: '2021/06/02 13:12:19 performing operation get: NoCredentialProviders: no valid providers in chain. Deprecated.
 For verbose messaging see aws.Config.CredentialsChainVerboseErrors
 '
 Failed to download S3 object, code 1, output: '', error: '2021/06/02 13:12:21 performing operation get: NoCredentialProviders: no valid providers in chain. Deprecated.
 For verbose messaging see aws.Config.CredentialsChainVerboseErrors
 '
 Failed to download S3 object, code 1, output: '', error: '2021/06/02 13:12:21 performing operation get: NoCredentialProviders: no valid providers in chain. Deprecated.
 For verbose messaging see aws.Config.CredentialsChainVerboseErrors
 '

Task 193 Started  Wed Jun  2 13:11:25 UTC 2021
Task 193 Finished Wed Jun  2 13:12:21 UTC 2021
Task 193 Duration 00:00:56
Task 193 error


Exit code 1
===== 2021-06-02 13:12:22 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=10.0.16.5 --deployment=cf-1f493917b1c1cf206ba6 deploy --no-redact /var/tempest/workspaces/default/deployments/cf-1f493917b1c1cf206ba6.yml"; Duration: 207s; Exit Status: 1
Exited with 1.
Exited with 1.
```

**Comment by kgyovai** [comment]
As a general architectural question, when installing a product like TAS/CF, what purpose do the Ops Manager and BOSH instances (as shown below) serve?

![image](https://user-images.githubusercontent.com/10728023/120493289-d4e9e900-c388-11eb-91a8-5a042fa750da.png)

My working assumption is the all `om` commands result in API calls to Ops Manager. Ops Manager then orchestrates the installation of TAS/CF. I can tell from the logs that BOSH is involved somehow and I can see that the CPU of the bosh/0 instance spikes (i.e. it's being used) but it isn't clear to me:

1. What the BOSH instance exists to do.
2. How the Ops Manager communicates with the BOSH instance.

**Comment by kgyovai** [comment]
I was able to resolve this issue by defining a vmextension.

```yaml
vmextensions-configuration:
  - name: iam-instance-profile
    cloud_properties:
      iam_instance_profile: ((instance_profile_name))
```

And then referencing it in the resource configuration for each instance defined in both the directory config and the TAS runtime config.

```yaml
resource-configuration:
  compilation:
    additional_networks: []
    additional_vm_extensions:
      - iam-instance-profile
  director:
    additional_networks: []
    additional_vm_extensions:
      - iam-instance-profile
```
